version: '3'

services:
  app:
    image: openjdk:17
    build:
      context: .
    working_dir: /app
    command: ["java", "-jar", "labEight-0.0.1-SNAPSHOT.jar"]
    volumes:
      - ./target:/app
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      my-network:

  mariadb:
    container_name: labEightMaria
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: student
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      my-network:
        ipv4_address: 192.168.1.3  # Set your desired IP address for mariadb service

networks:
  my-network:
    external: true
